CC = gcc

hello_threads: hello_threads.c
	$(CC) hello_threads.c -pthread -o hello_threads

hello_threads_multiple: hello_threads_multiple.c
	$(CC) hello_threads_multiple.c -pthread -o hello_threads_multiple


clean: 
	rm -f *.o hello_threads hello_threads_multiple